version: '3.8'

services:
  # PostgreSQL para el servicio de autenticación
  postgres:
    image: postgres:16-alpine
    container_name: bd_usuarios
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: usuarios_bd
    ports:
      - "5432:5432"
    volumes:
      - datos_postgres:/var/lib/postgresql/data
    networks:
      - red_tienda

  # MySQL para el servicio de catálogo
  mysql:
    image: mysql:8.0
    container_name: bd_productos
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: productos_bd
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - datos_mysql:/var/lib/mysql
    networks:
      - red_tienda

  # MongoDB para el servicio de pedidos
  mongo:
    image: mongo:7
    container_name: bd_pedidos
    environment:
      MONGO_INITDB_DATABASE: pedidos_bd
    ports:
      - "27017:27017"
    volumes:
      - datos_mongo:/data/db
    networks:
      - red_tienda

volumes:
  datos_postgres:
  datos_mysql:
  datos_mongo:

networks:
  red_tienda:
    driver: bridge